# Generated by Django 5.2.8 on 2026-04-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('notes', models.CharField(help_text='e.g. Floral · Fresh · Calm', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_info', models.CharField(help_text='e.g. 1 Bottle', max_length=100)),
                ('shipping_info', models.CharField(help_text='e.g. Free shipping (North Emirates)', max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
        ),
    ]
